TonsNeutros.Store/Controllers/BuyerController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.Blazor;
using TonsNeutros.Admin.Models;
using TonsNeutros.Store.Repositories;
using TonsNeutros.Store.Repositories.Interfaces;
using TonsNeutros.Store.ViewModels;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace TonsNeutros.Store.Controllers;

public class BuyerController : Controller
{
    private readonly IBuyerRepository _buyerRepository;
    private readonly IAddressRepository _addressRepository;
    private readonly UserManager<Buyer> _userManager;
    private readonly IHttpContextAccessor _httpContextAccessor;

    public BuyerController(IBuyerRepository buyerRepository, IAddressRepository addressRepository, UserManager<Buyer> userManager, IHttpContextAccessor httpContextAccessor)
    {
        _buyerRepository = buyerRepository;
        _addressRepository = addressRepository;
        _userManager = userManager;
        _httpContextAccessor = httpContextAccessor;
    }

    public IActionResult Edit()
    {
        var user = _httpContextAccessor.HttpContext.User;
        var buyerId = _userManager.GetUserId(user);
        
        var buyer = _buyerRepository.Buyers.FirstOrDefault(b => b.Id.Equals(buyerId));
        
        var address = _addressRepository.Addresses.FirstOrDefault(u => u.AddressId == buyer.AddressId);   

        if (buyer == null)
        {
            return RedirectToAction(nameof(Error), new { message = "User not found" });
        }

        var viewModel = new BuyerFormViewModel
        {
            Buyer = buyer,
            Address = address,

        };

        return View(viewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(BuyerFormViewModel viewModel)
    {
        var user = _httpContextAccessor.HttpContext.User;
        var buyerId = _userManager.GetUserId(user);

        var buyer = _buyerRepository.Buyers
            .FirstOrDefault(b => b.Id.Equals(buyerId));
        var address = _addressRepository.Addresses.FirstOrDefault(u => u.AddressId == buyer.AddressId);

        if (buyer == null)
        {
            return RedirectToAction(nameof(Error), new { message = "User not found" });
        }

        if (ModelState.IsValid)
        {
            _buyerRepository.Update(viewModel);
            return RedirectToAction("Index", "Home");

        }
        viewModel.Buyer = buyer;
        viewModel.Address = address;
        return View(viewModel);
    }
}

TonsNeutros.Store/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TonsNeutros.Admin.Models;
using TonsNeutros.Store.Repositories.Interfaces;
using static System.Runtime.InteropServices.JavaScript.JSType;
using TonsNeutros.Store.ViewModels;

namespace TonsNeutros.Store.Controllers;

public class OrderController : Controller
{
    private readonly IBuyerRepository _buyerRepository;
    private readonly IAddressRepository _addressRepository;
    private readonly UserManager<Buyer> _userManager;
    private readonly IHttpContextAccessor _httpContextAccessor;
    private readonly IOrderRepository _orderRepository;
    private readonly ShoppingCart _shoppingCart;

    public OrderController(IBuyerRepository buyerRepository, IAddressRepository addressRepository, UserManager<Buyer> userManager, IHttpContextAccessor httpContextAccessor, IOrderRepository orderRepository, ShoppingCart shoppingCart)
    {
        _buyerRepository = buyerRepository;
        _addressRepository = addressRepository;
        _userManager = userManager;
        _httpContextAccessor = httpContextAccessor;
        _orderRepository = orderRepository;
        _shoppingCart = shoppingCart;
    }

    [Authorize]
    public IActionResult Checkout()
    {
        var user = _httpContextAccessor.HttpContext.User;
        var buyerId = _userManager.GetUserId(user);

        var buyer = _buyerRepository.Buyers.FirstOrDefault(b => b.Id.Equals(buyerId));

        if (buyer == null)
        {
            return RedirectToAction(nameof(Error), new { message = "User not found" });
        }

        var address = _addressRepository.Addresses.FirstOrDefault(u => u.AddressId == buyer.AddressId);

        if (address == null)
        {
            return RedirectToAction(nameof(Error), new { message = "Address not found" });
        }

        var viewModel = new BuyerFormViewModel
        {
            Buyer = buyer,
            Address = address,

        };

        return View(viewModel);
    }

    [Authorize]
    [HttpPost]
    public IActionResult Checkout(Order order)
    {
        var user = _httpContextAccessor.HttpContext.User;
        var buyerId = _userManager.GetUserId(user);

        var buyer = _buyerRepository.Buyers.FirstOrDefault(b => b.Id.Equals(buyerId));
        if (buyer == null)
        {
            return RedirectToAction(nameof(Error), new { message = "User not found" });
        }
        order.BuyerId = buyerId;

        var address = _addressRepository.Addresses.FirstOrDefault(u => u.AddressId == buyer.AddressId);

        if (address == null)
        {
            return RedirectToAction(nameof(Error), new { message = "Address not found" });
        }
        order.AddressId = address.AddressId;


        int orderTotalItems = 0;
        decimal orderTotalPrice = 0.0m;

        //obtem os itens do carrinho de compra do cliente
        List<ShoppingCartItem> items = _shoppingCart.GetCartItems();
        _shoppingCart.CartItems = items;

        //verifica se existem itens no pedido
        if (_shoppingCart.CartItems.Count == 0)
        {
            ModelState.AddModelError("", "Your cart is empty.");
        }

        //calcula o total de itens e o total do pedido
        foreach (var item in items)
        {
            orderTotalItems += item.Quantity;
            orderTotalPrice += (item.Product.Price * item.Quantity);
        }

        //atribui os valores obtidos ao pedido
        order.TotalItemsOrder = orderTotalItems;
        order.TotalOrder = orderTotalPrice;

        //cria o pedido e os detalhes
        _orderRepository.CreateOrder(order);

        //define mensagens ao cliente
        ViewBag.CheckoutCompleteMessage = "Muito obrigado. A sua encomenda está a caminho.";
        ViewBag.TotalOrder = _shoppingCart.GetTotalCart();

        //limpa o carrinho do cliente
        _shoppingCart.CleanCart();

        //exibe a view com dados do cliente e do pedido
        return View("~/Views/Order/CheckoutComplete.cshtml", order);
    }
}

TonsNeutros.Store/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TonsNeutros.Admin.Models;
using TonsNeutros.Store.Repositories.Interfaces;
using TonsNeutros.Store.ViewModels;

namespace TonsNeutros.Store.Controllers;

public class ShoppingCartController : Controller
{
    private readonly IProductRepository _productRepository;
    private readonly ShoppingCart _shoppingCart;

    public ShoppingCartController(IProductRepository productRepository, ShoppingCart shoppingCart)
    {
        _productRepository = productRepository;
        _shoppingCart = shoppingCart;
    }

    [Authorize]
    public IActionResult Index()
    {
        var items = _shoppingCart.GetCartItems();
        _shoppingCart.CartItems = items;

        var shoppingCartVM = new ShoppingCartViewModel
        {
            ShoppingCart = _shoppingCart,
            ShoppingCartTotal = _shoppingCart.GetTotalCart(),
        };
        return View(shoppingCartVM);
    }

    [Authorize]
    public IActionResult AddItemShoppingCart(int productId)
    {
        var selectedProduct = _productRepository.Products.FirstOrDefault(p => p.ProductId == productId);
        if (selectedProduct != null)
        {
            _shoppingCart.AddToCart(selectedProduct);
        }
        return RedirectToAction("Index");
    }

    [Authorize]
    public IActionResult RemoveItemShoppingCart(int productId)
    {
        var selectedProduct = _productRepository.Products.FirstOrDefault(p => p.ProductId == productId);
        if (selectedProduct != null)
        {
            _shoppingCart.RemoveFromCart(selectedProduct);
        }
        return RedirectToAction("Index");
    }
}

TonsNeutros.Store/Views/Order/Checkout.cshtml
@model TonsNeutros.Store.ViewModels.BuyerFormViewModel

<div class="main-content-page">
    <div class="title-details">
        <h2> Dados de envio</h2>
        <a class="link-address" asp-controller="Buyer" asp-action="Edit">Alterar morada</a>
    </div>
    <div class="main-bg">
        <div class="address-meta">
            <span class="address-meta-text">@Model.Buyer?.Name</span>
            <span class="address-meta-text">@Model.Buyer?.Nif</span>
            <span class="address-meta-text">@Model.Buyer?.PhoneNumber</span>
            <span class="address-meta-text">@Model.Address?.Street</span>
            <span class="address-meta-text">@Model.Address?.Place</span>
            <span class="address-meta-text">@Model.Address?.ZipCode</span>
            <span class="address-meta-text">@Model.Address?.City</span>
            <span class="address-meta-text">@Model.Address?.Country</span>
        </div>
    </div>
    <form id="checkoutForm" asp-controller="Order" asp-action="Checkout" method="post">
        <div class="button-container">
            <a class="cancel-btn" asp-controller="ShoppingCart" asp-action="Index">Voltar ao Carrinho</a>
            <input class="order-btn" type="submit" value="Finalizar compra" />
        </div>
    </form>
</div>

TonsNeutros.Store/Views/Order/CheckoutComplete.cshtml
@model Order

<div class="main-content-page">
    <div class="title-details">
        <h2>@ViewBag.CheckoutCompleteMessage</h2>
    </div>
    <div class="main-bg">
        <div class="address-meta">
            <span class="address-meta-text">Cliente: <strong>@Model.Buyer?.Name</strong></span>
            <span class="address-meta-text">Contacto: <strong>@Model.Buyer?.PhoneNumber</strong></span>
            <span class="address-meta-text">Data de compra: <strong>@Model.OrderDate.ToString("dd/MM/yyyy")</strong></span>
            <span class="address-meta-text">Data de envio: <strong>@Model.OrderSentDate</strong></span>
        </div>
    </div>
    <div class="table-top"
        <div class="responsive-table">
            <table class="products-table">
                <thead>
                    <tr class="table-row table-row-header">
                        <th class="table-header">Produto</th>
                        <th class="table-header">Quantidade</th>
                        <th class="table-header">Preço</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model.ItemsOrder)
                    {
                        <tr class="table-row">
                            <td class="tablecel">
                                <div class="product-details">
                                    <img class="product-image" src="@Url.Content(item.Product.ImageURL)" alt="@item.Product.ProductName" />
                                    <span class="product-name">@item.Product.ProductName</span>
                                </div>
                            <td class="table-cel">@item.Quantity</td>
                            <td class="tablecel">@item.Product.Price.ToString("c")</td>
                        </tr>
                    }
                </tbody>
            </table>
            <div class="button-container">
                <a class="cancel-btn" asp-controller="Home" asp-action="Index">Voltar</a>
            </div>
        </div>
    </div>
</div>