TonsNeutros.Store/ViewModels/ShoppingCartViewModel.cs
using TonsNeutros.Admin.Models;

namespace TonsNeutros.Store.ViewModels;

public class ShoppingCartViewModel
{
    public ShoppingCart? ShoppingCart { get; set; }
    public decimal ShoppingCartTotal { get; set; }
}

TonsNeutros.Store/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TonsNeutros.Admin.Models;
using TonsNeutros.Store.Repositories.Interfaces;
using static System.Runtime.InteropServices.JavaScript.JSType;
using TonsNeutros.Store.ViewModels;

namespace TonsNeutros.Store.Controllers;

public class OrderController : Controller
{
    private readonly IBuyerRepository _buyerRepository;
    private readonly IAddressRepository _addressRepository;
    private readonly UserManager<Buyer> _userManager;
    private readonly IHttpContextAccessor _httpContextAccessor;
    private readonly IOrderRepository _orderRepository;
    private readonly ShoppingCart _shoppingCart;

    public OrderController(IBuyerRepository buyerRepository, IAddressRepository addressRepository, UserManager<Buyer> userManager, IHttpContextAccessor httpContextAccessor, IOrderRepository orderRepository, ShoppingCart shoppingCart)
    {
        _buyerRepository = buyerRepository;
        _addressRepository = addressRepository;
        _userManager = userManager;
        _httpContextAccessor = httpContextAccessor;
        _orderRepository = orderRepository;
        _shoppingCart = shoppingCart;
    }

    [Authorize]
    public IActionResult Checkout()
    {
        var user = _httpContextAccessor.HttpContext.User;
        var buyerId = _userManager.GetUserId(user);

        var buyer = _buyerRepository.Buyers.FirstOrDefault(b => b.Id.Equals(buyerId));

        if (buyer == null)
        {
            return RedirectToAction(nameof(Error), new { message = "User not found" });
        }

        var address = _addressRepository.Addresses.FirstOrDefault(u => u.AddressId == buyer.AddressId);

        if (address == null)
        {
            return RedirectToAction(nameof(Error), new { message = "Address not found" });
        }

        var viewModel = new BuyerFormViewModel
        {
            Buyer = buyer,
            Address = address,

        };

        return View(viewModel);
    }

    [Authorize]
    [HttpPost]
    public IActionResult Checkout(Order order)
    {
        var user = _httpContextAccessor.HttpContext.User;
        var buyerId = _userManager.GetUserId(user);

        var buyer = _buyerRepository.Buyers.FirstOrDefault(b => b.Id.Equals(buyerId));
        if (buyer == null)
        {
            return RedirectToAction(nameof(Error), new { message = "User not found" });
        }
        order.BuyerId = buyerId;

        var address = _addressRepository.Addresses.FirstOrDefault(u => u.AddressId == buyer.AddressId);

        if (address == null)
        {
            return RedirectToAction(nameof(Error), new { message = "Address not found" });
        }
        order.AddressId = address.AddressId;


        int orderTotalItems = 0;
        decimal orderTotalPrice = 0.0m;

        //obtem os itens do carrinho de compra do cliente
        List<ShoppingCartItem> items = _shoppingCart.GetCartItems();
        _shoppingCart.CartItems = items;

        //verifica se existem itens no pedido
        if (_shoppingCart.CartItems.Count == 0)
        {
            ModelState.AddModelError("", "Your cart is empty.");
        }

        //calcula o total de itens e o total do pedido
        foreach (var item in items)
        {
            orderTotalItems += item.Quantity;
            orderTotalPrice += (item.Product.Price * item.Quantity);
        }

        //atribui os valores obtidos ao pedido
        order.TotalItemsOrder = orderTotalItems;
        order.TotalOrder = orderTotalPrice;

        //cria o pedido e os detalhes
        _orderRepository.CreateOrder(order);

        //define mensagens ao cliente
        ViewBag.CheckoutCompleteMessage = "Muito obrigado. A sua encomenda está a caminho.";
        ViewBag.TotalOrder = _shoppingCart.GetTotalCart();

        //limpa o carrinho do cliente
        _shoppingCart.CleanCart();

        //exibe a view com dados do cliente e do pedido
        return View("~/Views/Order/CheckoutComplete.cshtml", order);
    }
}

TonsNeutros.Store/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using TonsNeutros.Admin.Migrations;
using TonsNeutros.Admin.Models;
using TonsNeutros.Store.Repositories.Interfaces;
using TonsNeutros.Store.ViewModels;

namespace TonsNeutros.Store.Controllers;

public class ProductController : Controller
{
    private readonly IProductRepository _productRepository;

    public ProductController(IProductRepository productRepository)
    {
        _productRepository = productRepository;
    }

    public IActionResult List(string category)
    {
        IEnumerable<Product> products;
        string currentCategory = string.Empty;

        if (string.IsNullOrEmpty(category))
        {
            products = _productRepository.Products.OrderBy(p => p.ProductId);
            currentCategory = "Produtos";
        }
        else
        {
            products = _productRepository.Products
                .Where(c => c.Category.CategoryName.Equals(category))
                .OrderBy(c => c.ProductName);
            currentCategory = category;
        }
        var productsListViewModel = new ProductListViewModel()
        {
            Products = products,
            CurrentCategory = currentCategory,
        };
        return View(productsListViewModel);
    }

    public IActionResult Details(int productid)
    {
        var product = _productRepository.Products.FirstOrDefault(p => p.ProductId == productid);
        return View(product);
    }

    public ViewResult Search(string searchString)
    {
        IEnumerable<Product> products;
        string currentCategory = string.Empty;

        if (string.IsNullOrEmpty(searchString))
        {
            products = _productRepository.Products.OrderBy(p =>p.ProductId);
            currentCategory = "Produtos";
        }
        else
        {
            products = _productRepository.Products.Where(p=>p.ProductName.ToLower().Contains(searchString.ToLower()));

            if(products.Any())
                currentCategory = "Produtos";
            else
                currentCategory = "Nenhum produto foi encontrado";
        }
        return View("~/Views/Product/List.cshtml", new ProductListViewModel
        {
            Products = products,
            CurrentCategory = currentCategory,

        });
    }
}

TonsNeutros.Store/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TonsNeutros.Admin.Models;
using TonsNeutros.Store.Repositories.Interfaces;
using TonsNeutros.Store.ViewModels;

namespace TonsNeutros.Store.Controllers;

public class ShoppingCartController : Controller
{
    private readonly IProductRepository _productRepository;
    private readonly ShoppingCart _shoppingCart;

    public ShoppingCartController(IProductRepository productRepository, ShoppingCart shoppingCart)
    {
        _productRepository = productRepository;
        _shoppingCart = shoppingCart;
    }

    [Authorize]
    public IActionResult Index()
    {
        var items = _shoppingCart.GetCartItems();
        _shoppingCart.CartItems = items;

        var shoppingCartVM = new ShoppingCartViewModel
        {
            ShoppingCart = _shoppingCart,
            ShoppingCartTotal = _shoppingCart.GetTotalCart(),
        };
        return View(shoppingCartVM);
    }

    [Authorize]
    public IActionResult AddItemShoppingCart(int productId)
    {
        var selectedProduct = _productRepository.Products.FirstOrDefault(p => p.ProductId == productId);
        if (selectedProduct != null)
        {
            _shoppingCart.AddToCart(selectedProduct);
        }
        return RedirectToAction("Index");
    }

    [Authorize]
    public IActionResult RemoveItemShoppingCart(int productId)
    {
        var selectedProduct = _productRepository.Products.FirstOrDefault(p => p.ProductId == productId);
        if (selectedProduct != null)
        {
            _shoppingCart.RemoveFromCart(selectedProduct);
        }
        return RedirectToAction("Index");
    }
}

TonsNeutros.Store/Views/ShoppingCart/Index.cshtml
@model ShoppingCartViewModel

<div class="content">
    @if (Model == null || Model.ShoppingCart == null || Model.ShoppingCart.CartItems == null || !Model.ShoppingCart.CartItems.Any())
    {
        <h2 class="center"> Your shopping cart is empty.</h2>
    }
    else
    {
        <div class="responsive-table">
            <table class="products-table">
                <thead>
                    <tr class="table-row table-row-header">
                        <th class="table-header">Produto</th>
                        <th class="table-header">Quantidade</th>
                        <th class="table-header">Preço</th>
                        <th class="table-header">Subtotal</th>
                        <th class="table-header"></th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model.ShoppingCart.CartItems)
                    {
                        <tr class="table-row">
                            <td class="tablecel">
                                <div class="product-details">
                                    <img class="product-image" src="@Url.Content(item.Product.ImageURL)" alt="@item.Product.ProductName" />
                                    <span class="product-name">@item.Product.ProductName</span>
                                </div>
                            <td class="table-cel">@item.Quantity</td>
                            <td class="tablecel">@item.Product.Price.ToString("c")</td>
                            <td class="tablecel-price">@((item.Quantity * item.Product.Price).ToString("c"))</td>
                            <td class="tablecel-delete">
                                <a asp-controller="ShoppingCart" asp-action="RemoveItemShoppingCart" asp-route-productId="@item.Product.ProductId">
                                    <img class="img-delete" src="~/images/delete.png" alt="Remove from Cart" />
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot class="table-footer">
                    <tr>
                        <td colspan="4" class="table-footer-total">Total: @Model.ShoppingCartTotal.ToString("c")</td>
                    </tr>
                </tfoot>
            </table>
            <div class="button-container">
                <a class="cancel-btn" asp-controller="Product" asp-action="List">Adicionar produto</a>
                <a class="order-btn" asp-controller="Order" asp-action="Checkout">Comprar</a>
            </div>
        </div>
    }
</div>